apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: minio
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /app
          name: minio
      volumes:
      - name: minio
        persistentVolumeClaim:
          claimName: s3-minio