apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: kibana-kb-https
  namespace: elastic-stack
spec:
  insecureSkipVerify: true

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mon
  namespace: elastic-stack
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mon.immi.gov.bt`)
      kind: Rule
      services:
        - name: kibana-kb-http
          port: 5601
          scheme: https
          serversTransport: kibana-kb-https
  tls:
    secretName: cert-mon.immi.gov.bt
