apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: admin-auth
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admin-auth
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: admin-portal
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admin-portal
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: client-auth
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-auth
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: common-data
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: common-data
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pii
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pii
  minReplicas: 10
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tourist-visa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tourist-visa
  minReplicas: 4
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: visa-portal
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: visa-portal
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bms-pre-registration
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bms-pre-registration
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: watchlist
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: watchlist
  minReplicas: 4
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bms
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bms
  minReplicas: 10
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mrz
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mrz
  minReplicas: 5
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 1024Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: non-tourist-visa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: non-tourist-visa
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: casual-visitor
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: casual-visitor
  minReplicas: 10
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: report
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: report
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: visa-on-arrival
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: visa-on-arrival
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: route-permit
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: route-permit
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: permit
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: permit
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: enrollment
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: enrollment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: offence
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: offence
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 256Mi
        type: AverageValue