kind: Service
apiVersion: v1
metadata:
  name: traefik2
  namespace: traefik
  labels:
    app.kubernetes.io/instance: traefik-traefik2
    app.kubernetes.io/name: traefik2
spec:
  ports:
    - name: web2
      protocol: TCP
      port: 80
      targetPort: web
    - name: websecure2
      protocol: TCP
      port: 443
      targetPort: websecure
  selector:
    app.kubernetes.io/name: traefik
  type: LoadBalancer
  loadBalancerIP: 103.252.84.41
