---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
  namespace: dev-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql
            - name: PMA_PORT
              value: "3306"
            - name: UPLOAD_LIMIT
              value: 500M
            - name: PMA_USER_CONFIG_BASE64
              valueFrom:
                secretKeyRef:
                  name: my-phpmyadmin-config
                  key: PMA_USER_CONFIG_BASE64
---
apiVersion: v1
kind: Service
metadata:
  name: dev-phpmyadmin
  namespace: dev-db
spec:
  type: ClusterIP
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
