kind: Secret
apiVersion: v1
metadata:
  name: my-phpmyadmin-config
  namespace: dev-db  
data:
  PMA_USER_CONFIG_BASE64: >-
    UEQ5d2FIQUtKR05tWjFzblZHaGxiV1ZOWVc1aFoyVnlKMTBnUFNCbVlXeHpaVHNLSkdObVoxc25WR2hsYldWRVpXWmhkV3gwSjEwOUlDZHRaWFJ5YnljN0NqOCs=
type: Opaque
