apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry.doi.gov.bt
  namespace: harbor
spec:
  secretName: cert-registry.doi.gov.bt
  dnsNames:
  - registry.doi.gov.bt
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer