apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: support.immi.gov.bt
  namespace: prod
spec:
  secretName: cert-support.immi.gov.bt
  dnsNames:
  - support.immi.gov.bt
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer