apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immi.doi.gov.bt
  namespace: prod
spec:
  secretName: cert-prod-doi.gov.bt
  dnsNames:
  - immi.doi.gov.bt
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer