apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mrz.ped.immi.gov.bt
  namespace: prod
spec:
  secretName: cert-mrz.ped.immi.gov.bt
  dnsNames:
  - mrz.ped.immi.gov.bt
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer