apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immi.gov.bt
  namespace: prod
spec:
  secretName: cert-prod-immi.gov.bt
  dnsNames:
  - immi.gov.bt
  - www.immi.gov.bt
  - api.immi.gov.bt
  - bms.immi.gov.bt
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer