apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev.doi.gov.bt
  namespace: dev
spec:
  secretName: cert-dev.doi.gov.bt
  dnsNames:
  - dev-visa.doi.gov.bt
  - dev-bms.doi.gov.bt
  - dev-admin-ims.doi.gov.bt
  - dev-api-ims.doi.gov.bt
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer