apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test.doi.gov.bt
  namespace: rook-ceph
spec:
  secretName: cert-test.doi.gov.bt
  dnsNames:
  - test.doi.gov.bt
  - test-gw.doi.gov.bt
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer